import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence, useReducedMotion } from 'framer-motion';
import { ChevronUp } from 'lucide-react';
import { toast } from 'sonner';
import { useWhispers } from '@/hooks/useWhispers';

interface WhisperStripProps {
  /** When true, renders only the active whisper with no chrome (used in Minimalist Mode). */
  bare?: boolean;
  /**
   * When true, the strip pauses its rotation. Used to coordinate visual
   * priority — if the Pivot pulse is firing or a sheet is open, the
   * ticker holds steady so only one element competes for attention.
   */
  paused?: boolean;
}

const ROTATE_MS = 7000;

/**
 * The Whisper Strip — single-line ticker, one whisper at a time.
 *
 * Whispers are now generated by `useWhispers()` based on time of day,
 * simulated proximity, and itinerary state.
 */
const WhisperStrip = ({ bare = false, paused: externalPaused = false }: WhisperStripProps) => {
  const { whispers, dismiss, restore } = useWhispers();
  const reduceMotion = useReducedMotion();
  const [index, setIndex] = useState(0);
  const [expanded, setExpanded] = useState(false);
  const [hoverPaused, setHoverPaused] = useState(false);
  const startY = useRef<number | null>(null);
  // Combined pause: hover, expanded, parent signal, or reduced-motion all halt rotation.
  const paused = hoverPaused || externalPaused || !!reduceMotion;

  // Reset to head when a new whisper arrives.
  useEffect(() => {
    setIndex(0);
  }, [whispers[0]?.id]);

  useEffect(() => {
    if (whispers.length <= 1 || paused || expanded) return;
    const t = setInterval(() => {
      setIndex((i) => (i + 1) % whispers.length);
    }, ROTATE_MS);
    return () => clearInterval(t);
  }, [whispers.length, paused, expanded]);

  const current = whispers[index];

  const onTouchStart = (e: React.TouchEvent) => {
    startY.current = e.touches[0].clientY;
  };

  const onTouchEnd = (e: React.TouchEvent) => {
    if (startY.current === null) return;
    const delta = e.changedTouches[0].clientY - startY.current;
    if (delta < -40) {
      // Swipe up — dismiss with a 4s undo so a stray gesture isn't fatal.
      if (current?.id) {
        const dismissed = current;
        dismiss(dismissed.id);
        setIndex(0);
        toast('Whisper hushed.', {
          description: dismissed.text.slice(0, 80),
          duration: 4000,
          action: restore
            ? { label: 'Undo', onClick: () => restore(dismissed.id) }
            : undefined,
        });
      }
    } else if (delta > 40) {
      // Swipe down — expand history
      setExpanded(true);
      setHoverPaused(true);
    }
    startY.current = null;
  };

  if (!current) {
    if (bare) return null;
    return (
      <div className="w-full px-4">
        <div className="text-center py-2">
          <span className="font-sans text-[10px] text-muted-foreground/60 italic">All caught up.</span>
        </div>
      </div>
    );
  }

  if (bare) {
    return (
      <div className="text-center px-6">
        <AnimatePresence mode="wait">
          <motion.p
            key={current.id}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.4 }}
            className="font-display italic text-xl text-foreground leading-relaxed"
          >
            {current.text}
          </motion.p>
        </AnimatePresence>
      </div>
    );
  }

  return (
    <div className="w-full px-4">
      <div
        className="relative bg-card/60 backdrop-blur-sm border border-border/60 rounded-full overflow-hidden"
        onTouchStart={onTouchStart}
        onTouchEnd={onTouchEnd}
        onMouseEnter={() => setHoverPaused(true)}
        onMouseLeave={() => setHoverPaused(false)}
      >
        {/* Single-line ticker */}
        <div className="flex items-center px-4 py-2.5 gap-3 min-h-[40px]">
          <div className="w-1.5 h-1.5 rounded-full bg-accent shrink-0" />
          <div className="flex-1 min-w-0 overflow-hidden">
            <AnimatePresence mode="wait">
              <motion.p
                key={current.id}
                initial={{ opacity: 0, x: 16 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -16 }}
                transition={{ duration: 0.3 }}
                className="font-sans text-[11px] text-foreground truncate"
              >
                {current.text}
              </motion.p>
            </AnimatePresence>
          </div>
          <button
            onClick={() => setExpanded((v) => !v)}
            className="bg-transparent border-none cursor-pointer p-1 opacity-50 hover:opacity-100 transition-opacity"
            aria-label="Show whisper history"
          >
            <ChevronUp
              size={12}
              className={`text-muted-foreground transition-transform ${expanded ? '' : 'rotate-180'}`}
            />
          </button>
        </div>

        {/* History — expanded view */}
        <AnimatePresence>
          {expanded && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="overflow-hidden border-t border-border/60"
            >
              <div className="px-4 py-2 space-y-1.5">
                {whispers.slice(0, 5).map((w) => (
                  <div key={w.id} className="flex items-start gap-2 py-1">
                    <span className="font-sans text-[8px] text-muted-foreground tabular-nums shrink-0 mt-0.5">
                      {w.time}
                    </span>
                    <p className="font-sans text-[10px] text-foreground/80 leading-relaxed">
                      {w.text}
                    </p>
                  </div>
                ))}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default WhisperStrip;
